"""empty message

Revision ID: 41abe3b30c7a
Revises: 
Create Date: 2024-12-11 16:31:30.504735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41abe3b30c7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_number', sa.String(), nullable=True),
    sa.Column('question1', sa.String(), nullable=True),
    sa.Column('question2', sa.String(), nullable=True),
    sa.Column('question3', sa.String(), nullable=True),
    sa.Column('question4', sa.String(), nullable=True),
    sa.Column('question5', sa.String(), nullable=True),
    sa.Column('question6', sa.String(), nullable=True),
    sa.Column('question7', sa.String(), nullable=True),
    sa.Column('question8', sa.String(), nullable=True),
    sa.Column('question9', sa.String(), nullable=True),
    sa.Column('question10', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answers_user_number'), ['user_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answers_user_number'))

    op.drop_table('answers')
    # ### end Alembic commands ###
